version: '3.8'

services:
  artifactory:
    build:
      context: .
      dockerfile: Dockerfile
    volume:
     - ./system.yaml:/opt/jfrog/artifactory/var/etc/system.yaml
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # Root password for MariaDB
      MYSQL_DATABASE: artdb          # Name of the database to be created
      MYSQL_USER: artifactory            # User for the database
      MYSQL_PASSWORD: password